### ISSUE TITLE
组件slot-scope提示父节点必须为element

### ISSUE THREAD

**Issue by wangjunget** [ant-mini-program/vscode-alipay-minicode#1]
![image](https://user-images.githubusercontent.com/39700548/127800246-c0140df6-445e-44ed-b927-fe1f61ff43d8.png)

**Comment by bytemain** [comment]
已确认，等待后续修复。

**Comment by bytemain** [comment]
同学你好，能给一下你出错的这段代码吗？

按照 https://opendocs.alipay.com/mini/framework/component-template 文档中的例子测试是成功的。

**Comment by wangjunget** [comment]
```html
<table class="data-table" dataSource="{{ userList }}" hasBorder="{{ true }}">
  <table-column title="序号" align="center" width="100px">
    <view slot-scope="x" class="name"> 
      {{x.index + 1}}
    </view>
  </table-column>
  <table-column title="子账号" align="center">
    <view slot-scope="x" class="status"> 
      
    </view>
  </table-column>
  <table-column title="状态" align="center">
    <view slot-scope="x" class="name"> 
      
    </view>
  </table-column>
  <table-column title="操作" align="center">
    <view slot-scope="x">
      <text>修改权限</text>
    </view>
  </table-column>
</table>
```
这一段代码，使用```table```组件

**Comment by bytemain** [comment]
你好，我们打包了一个临时修复版，你可以测试一下还会不会有这个问题。

https://files.alicdn.com/tpsservice/c6515a1c80901eaa7c9a101503ba28f0.zip

安装方式：
1. 下载 - 解压出 .vsix 文件
2. 打开 VSC 插件页面，右上角三个点，选择【从 VSIX 安装】
![Shot 2021-08-03 at 13 30 07](https://user-images.githubusercontent.com/13938334/127962845-788862c8-d51b-4302-87cc-91e3f9e33895.png)

没有问题的话修复将在下个正式版本应用。

**Comment by wangjunget** [comment]
> 你好，我们打包了一个临时修复版，你可以测试一下还会不会有这个问题。
> 
> https://files.alicdn.com/tpsservice/c6515a1c80901eaa7c9a101503ba28f0.zip
> 
> 安装方式：
> 
> 1. 下载 - 解压出 .vsix 文件
> 2. 打开 VSC 插件页面，右上角三个点，选择【从 VSIX 安装】
>    ![Shot 2021-08-03 at 13 30 07](https://user-images.githubusercontent.com/13938334/127962845-788862c8-d51b-4302-87cc-91e3f9e33895.png)
> 
> 没有问题的话修复将在下个正式版本应用。

好的，我试下

**Comment by wangjunget** [comment]
可以了👍👍👍

**Comment by bytemain** [comment]
等待下个版本修复
