### ISSUE TITLE
今天VSCode更新minicode插件后TypeScript处于崩溃状态

### ISSUE THREAD

**Issue by puxiao** [ant-mini-program/vscode-alipay-minicode#14]
VSCode 底部的 TypeScript 一直处于转圈状态，然后写代码无任何 TypeScript 检查和提示。
提示信息为：
The JS/TS language service immediately crashed 5 times. The service will not be restarted.
This may be caused by a plugin contributed by one of these extensions: alipay.minicode.
Please try disabling these extensions before filing an issue against VS Code.

我卸载minicode插件重启VSCode后，TS 恢复正常。

VSCode版本：1.85.0
Window10 64位系统

**Comment by bytemain** [comment]
你好，我们正在处理这个问题。

**Comment by bytemain** [comment]
插件市场已经更新 1.16.2，请尝试刷新，市场会有一定的延迟。
可以直接下载这个版本

[minicode-1.16.2.vsix.zip](https://github.com/ant-mini-program/vscode-alipay-minicode/files/13775089/minicode-1.16.2.vsix.zip)
