### ISSUE TITLE
Path must be inside your project root directory

### ISSUE THREAD

**Issue by zephyr-yang66** [ant-mini-program/vscode-alipay-minicode#2]
在VS Code 中通过插件创建小程序页面，报错Path must be inside your project root directory。
在小程序项目中，根路径往往是一些构建文件。
另外希望能够创建ts小程序文件

**Comment by bytemain** [comment]
这个报错应该是因为要创建的页面不在 mini.project.json 设置的 `miniprogramRoot` 中。

这个已经有计划去除。你可以暂时现在某个文件中创建好再复制过来。

**Comment by bytemain** [comment]
支持创建 ts 小程序文件的话，方便问一下你现在用的是什么小程序开发框架吗？

我们要了解一下如何区分你的框架是用 js 还是 ts 呢~

**Comment by bytemain** [comment]
1.6.4 会带上这两个特性。

**Comment by bytemain** [comment]
https://github.com/ant-mini-program/vscode-alipay-minicode/commit/042c207963db9ee5529064895adb9698e1ee3036
加上了如何创建 ts/less 文件的文档

标题所说的问题已经解决了。
