### ISSUE TITLE
There is no formatter for 'axml' files installed

### ISSUE THREAD

**Issue by 0xUniko** [ant-mini-program/vscode-alipay-minicode#3]
在axml文件中按vscode的格式化快捷键 shift+alt+f，提示没有安装能格式化axml的插件，可是我看见支付宝小程序开发助手这个插件的介绍里面是可以格式化的：

> 提供 axml、acss 的高亮、对齐、语法检测、格式化

**Comment by bytemain** [comment]
我本地试了一下是可以 format 的，也许是插件并没有启动。
请问一下：
请问当前项目目录是否有以下文件：
• app.json
• app.js
• mini.project.json
• ext.json
• plugin.json

插件只会在有这些文件其中之一的时候启动。

最好可以截图一下你的根目录文件~

**Comment by 0xUniko** [comment]
谢谢回复，缺了ext.json, mini.project.json, plugin.json，手动创建三个空文件之后就可以用了

我是直接用官方的todo-app的例子改的自己的小程序，里面没有这三个文件，vscode插件里也没有相应的说明，所以还是希望提个小小的建议，补充一下说明方便之后的人不踩坑~

**Comment by bytemain** [comment]
其实是只要其中之一的文件加好了，官方的 todo-app 的例子是指开发者工具里的吗？

**Comment by bytemain** [comment]
收到你的建议~

**Comment by 0xUniko** [comment]
> 

是的，用开发者工具创建的todo-app

**Comment by bytemain** [comment]
好的，我们来优化一下这些问题

**Comment by 0xUniko** [comment]
但是app.json和app.js是有的，之前是用不了的

**Comment by bytemain** [comment]
看了看代码，确实是支持配置 app.json 的。
我本地创建了一个 todoApp，也是能 format 的。

你能否先删除一下刚创建的三个文件，看是否能启动。
然后看一下 输出这一栏中的
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/13938334/157833637-1b85399d-913c-4e33-bfe2-5b237be53785.png">

这两个选项有没有报错？

**Comment by 0xUniko** [comment]
删除了，现在是正常了，重启了vscode之后仍然正常，问题没法复现了

谢谢你们的耐心回复~
