### ISSUE TITLE
【新建】希望右键新建的时候可以选择TS、Less等

### ISSUE THREAD

**Issue by Indomite** [ant-mini-program/vscode-alipay-minicode#4]
希望右键新建的时候可以选择TS、Less等

**Comment by Indomite** [comment]
Current Version：
![image](https://user-images.githubusercontent.com/52552604/167986011-84db8e0c-55e4-43c0-9c04-57c0af1c71ce.png)

**Comment by bytemain** [comment]
你好，可以描述清楚一些问题吗

**Comment by Indomite** [comment]
> 你好，可以描述清楚一些问题吗

sorry，刚刚没写完就去忙别的了，就是希望右键新建的时候可以选择TS、Less等，不然还得改下文件名
（我在另一个issue中看到说1.6.10版本可以，但是并没有看到，不知道是不是我不会用 ）

**Comment by bytemain** [comment]
你好，现在 1.6.10 在代码层面其实已经支持创建了。。。。。

但是这个依赖 mini.project.json 的新格式，但是文档啊啥的都没出来，所以还没有公布。等到 IDE 3.0 beta 后我们会把所有的 ts less 的能力开放出去，到时候就可以创建了。

预计在本月会开放 IDE 3.0

**Comment by Indomite** [comment]
> 你好，现在 1.6.10 在代码层面其实已经支持创建了。。。。。
> 
> 但是这个依赖 mini.project.json 的新格式，但是文档啊啥的都没出来，所以还没有公布。等到 IDE 3.0 beta 后我们会把所有的 ts less 的能力开放出去，到时候就可以创建了。
> 
> 预计在本月会开放 IDE 3.0

了解了，thinks～

**Comment by bytemain** [comment]
https://github.com/ant-mini-program/vscode-alipay-minicode/commit/042c207963db9ee5529064895adb9698e1ee3036

加上了如何创建 ts/less 的文档
