### ISSUE TITLE
格式化 会丢代码

### ISSUE THREAD

**Issue by weiminghaoo** [ant-mini-program/vscode-alipay-minicode#7]
每次格式化都意外的丢代码，坑死人  v1.6.14版本

**Comment by bytemain** [comment]
是格式化 axml 文件吗？能给个 axml 文件的例子吗？我这边并没有出现过这种情况

**Comment by bytemain** [comment]
是不是因为装了 xml 的格式化插件？然后 axml 和 xml 文件关联上了？

**Comment by weiminghaoo** [comment]
> 

没装

**Comment by weiminghaoo** [comment]
> 是格式化 axml 文件吗？能给个 axml 文件的例子吗？我这边并没有出现过这种情况

上个版本的好像没这个问题

**Comment by weiminghaoo** [comment]
> 是格式化 axml 文件吗？能给个 axml 文件的例子吗？我这边并没有出现过这种情况

把文件复制一份都复现不了 ，就很奇怪，

**Comment by weiminghaoo** [comment]
> 是不是因为装了 xml 的格式化插件？然后 axml 和 xml 文件关联上了？

我录了个视频    [https://t.wss.ink/f/8glpifr5ryl](https://t.wss.ink/f/8glpifr5ryl) 复制链接到浏览器打开

**Comment by bytemain** [comment]
看视频的表现，是指每次注释会被移除掉吗？

![CleanShot 2022-06-02 at 17 04 31@2x](https://user-images.githubusercontent.com/13938334/171595784-9c538ee1-1326-47ff-a450-061e7e47744d.png)

可以尝试把插件禁用掉看还有没有这个问题。

**Comment by weiminghaoo** [comment]
> 看视频的表现，是指每次注释会被移除掉吗？
> 
> ![CleanShot 2022-06-02 at 17 04 31@2x](https://user-images.githubusercontent.com/13938334/171595784-9c538ee1-1326-47ff-a450-061e7e47744d.png)
> 
> 可以尝试把插件禁用掉看还有没有这个问题。

不是注释 看注释上边或者下边的代码，随意修改点东西，再格式化，indexSjs.xxxxxx丢失的内容都不一样。把插件禁用就好了，现在用回了AXML Language Features

**Comment by bytemain** [comment]
好的，我们来看一下~

**Comment by bytemain** [comment]
始终无法复现。。。
<img width="976" alt="CleanShot 2022-06-06 at 14 32 50@2x" src="https://user-images.githubusercontent.com/13938334/172107940-2002a8e1-99ff-44fb-ac85-41be608a1e16.png">


请问可以给一下安装的插件列表吗？
```
code --list-extensions
```

因为我们的插件会将 axml 关联到了 xml，所以想看看是不是有 xml 的插件

**Comment by weiminghaoo** [comment]
> 始终无法复现。。。 <img alt="CleanShot 2022-06-06 at 14 32 50@2x" width="976" src="https://user-images.githubusercontent.com/13938334/172107940-2002a8e1-99ff-44fb-ac85-41be608a1e16.png">
> 
> 请问可以给一下安装的插件列表吗？
> 
> ```
> code --list-extensions
> ```
> 
> 因为我们的插件会将 axml 关联到了 xml，所以想看看是不是有 xml 的插件

➜ code --list-extensions
aaron-bond.better-comments
alefragnani.project-manager
alipay.appx-axml-language
alipay.minicode
bierner.markdown-preview-github-styles
christian-kohler.path-intellisense
CoenraadS.bracket-pair-colorizer-2
david-rickard.git-diff-and-merge-tool
dbaeumer.vscode-eslint
dlhtx.uniapp-snippet
eamodio.gitlens
EditorConfig.EditorConfig
Equinusocio.moxer-icons
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
formulahendry.code-runner
freedy.sjs
GitHub.copilot
GitHub.github-vscode-theme
Gruntfuggly.todo-tree
hediet.vscode-drawio
HookyQR.beautify
howardzuo.vscode-git-tags
humao.rest-client
in4margaret.compareit
jasonnutter.search-node-modules
jcbuisson.vue
joeandaverde.vscode-elm-jump
k--kato.intellij-idea-keybindings
kisstkondoros.vscode-gutter-preview
lihuiwang.vue-alias-skip
lokalise.i18n-ally
maixiaojie.git-emoji-zh
MamoruDS.workspace-cacheclean
medzhidov.hex-rgba-converter
mhutchie.git-graph
michelemelluso.code-beautifier
miguelsolorio.fluent-icons
monokai.theme-monokai-pro-vscode
moshfeu.diff-merge
mrmaoddxxaa.create-uniapp-view
MS-CEINTL.vscode-language-pack-zh-hans
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
nomi9995.intellij-merge-tool
OBKoro1.korofileheader
octref.vetur
qiu8310.minapp-vscode
rangav.vscode-thunder-client
ravenq.vscode-goto-node-modules
sburg.vscode-javascript-booster
sdras.vue-vscode-snippets
Shan.code-settings-sync
shenjiaolong.vue-helper
steoates.autoimport
svenzhao.var-translation
vincaslt.highlight-matching-tag
VisualStudioExptTeam.intellicode-api-usage-examples
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
Vue.volar
weimh.ali-miniapp-createpage
wix.vscode-import-cost
xabikos.JavaScriptSnippets
xiashui.uview-snippet
yzhang.markdown-all-in-one
zhengjiaqi.px-to-rpx
zhuzhuzhuzhuxia.vscode-path-alias

**Comment by bytemain** [comment]
下个版本我们先下掉我们的 format 能力~

**Comment by bytemain** [comment]
上面那个视频过期了，请问可以再发一次吗

**Comment by bytemain** [comment]
1.6.24 已经发布，移除了格式化的能力，待修复后重新上线。

**Comment by bytemain** [comment]
应该已经定位到了问题，我们的缓存策略有问题，导致 format 的时候取到的是之前编辑的文档，导致格式化问题。1.6.25 已经修复。只会出现在用户部分选中代码的情况下。

**Comment by bytemain** [comment]
1.7.0 已发布。
