### ISSUE TITLE
format 丢失代码

### ISSUE THREAD

**Issue by liangpeng98** [ant-mini-program/vscode-alipay-minicode#8]
格式化代码会丢失，有些注释也会被解开

**Comment by bytemain** [comment]
你好，可以给一个例子吗

**Comment by bytemain** [comment]
1.6.24 已经发布，移除了格式化的能力，待修复后重新上线。

**Comment by liangpeng98** [comment]
好的

**Comment by bytemain** [comment]
应该已经定位到了问题，我们的缓存策略有问题，导致 format 的时候取到的是之前编辑的文档，导致格式化问题。1.6.25 已经修复。只会出现在用户部分选中代码的情况下。

**Comment by bytemain** [comment]
1.7.0 已发布。
